GRILLES = [
    # GRILLE 1
    [
        "A pris un télésiège avec Stéphane",
        "A parlé de moto avec Maxence",
        "Offrir un shot à quelqu'un",
        "A déjà fait du hors-piste",
        "Skie depuis plus de 10 ans",
        "A fait une chute aujourd'hui",
        "Quelqu'un qui veut aller à Saint Barth",
        "A parlé de change avec Erwan",
        "A fait un selfie avec toute l'équipe LV présente",
    ],
    # GRILLE 2
    [
        "Trouver quelqu'un qui déteste les tire fesses",
        "Quelqu'un qui a rejoint AI Builders cette année",
        "A parlé de change avec Erwan",
        "Quelqu'un qui est né le même mois que toi",
        "Quelqu'un qui parle 3 langues",
        "A sorti son ordi sur les pistes",
        "A fait du snowboard",
        "A fait de la luge",
        "A fait un discours",
    ],
    # GRILLE 3
    [
        "Quelqu'un qui est né le même mois que toi",
        "A déjà fait du hors-piste",
        "Skie depuis plus de 10 ans",
        "Préfère l'après ski que le ski",
        "A fait une chute aujourd'hui",
        "Quelqu'un qui a un animal de compagnie",
        "A eu un call client dans le weekend",
        "A envoyé un mail pro sur une piste",
        "A fait une photo influenceur(se) au sommet",
    ],
    # GRILLE 4
    [
        "A déjà fait du hors-piste",
        "Quelqu'un qui a déjà perdu ses skis / bâtons",
        "Quelqu'un qui a rejoint l'entreprise cette année",
        "A parlé de la Maif avec Martin M",
        "A sorti son ordi sur les pistes",
        "Préfère l'après ski que le ski",
        "Quelqu'un qui parle 3 langues",
        "Offrir un shot à quelqu'un",
        "A fait un discours",
    ],
    # GRILLE 5
    [
        "A fait l'éveil du flocon",
        "Faire un selfie avec 3 collègues",
        "Quelqu'un qui parle 3 langues",
        "Skie depuis plus de 10 ans",
        "A chanté une chanson en karaoké",
        "Quelqu'un qui est né le même mois que toi",
        "Faire une photo d'équipe sur le télésiège",
        "Offrir un shot à quelqu'un",
        "Quelqu'un qui a vécu à l'étranger",
    ],
    # GRILLE 6
    [
        "A parlé de moto avec Maxence",
        "A sorti son ordi sur les pistes",
        "A eu un call client",
        "A envoyé un mail pro sur une piste",
        "A fait rire 5 personnes avec la même blague",
        "A collé un sticker AI Builders sur les pistes",
        "Faire un selfie avec 3 collègues",
        "A déjà fait du hors-piste",
        "Quelqu'un qui est né le même mois que toi",
    ],
    # GRILLE 7
    [
        "Faire un selfie avec 3 collègues",
        "Quelqu'un qui a déjà fait un marathon",
        "A eu un call client",
        "Quelqu'un qui déteste le ski",
        "A dansé avec Nathan",
        "A collé un sticker AI Builders sur les pistes",
        "Quelqu'un qui est né le même mois que toi",
        "A travaillé pour La Poste",
        "Offrir un shot à quelqu'un",
    ],
    # GRILLE 8
    [
        "Trouver quelqu'un qui déteste les tire fesses",
        "A sorti son ordi sur les pistes",
        "A descendu une piste noire (sans tomber)",
        "A skié sans veste",
        "Offrir un shot à quelqu'un",
        "A fait un discours",
        "A dansé avec Nathan",
        "Quelqu'un qui a vécu à l'étranger",
        "Quelqu'un qui a dévalé une piste sur les fesses",
    ],
    # GRILLE 9
    [
        "A déjà dévalé une piste sur les fesses",
        "A déjà fait du hors-piste",
        "A fait rire 5 personnes avec la même blague",
        "A descendu une piste noire (sans tomber)",
        "A skié sans veste",
        "A envoyé un mail pro sur une piste",
        "A chanté une chanson en karaoké",
        "A parlé de la Belgique avec Chloé ou Jean",
        "A fait l'éveil du flocon",
    ],
    # GRILLE 10
    [
        "A sorti son ordi sur les pistes",
        "A dévalé une piste sur les fesses",
        "A un animal de compagnie",
        "Skie depuis plus de 10 ans",
        "A fait du snowboard",
        "A fait un selfie avec toute l'équipe LV présente",
        "A parlé de la Maif avec Martin M",
        "Est sur une selfie d'Emmanuel",
        "A envoyé un mail pro sur une piste",
    ],
    # GRILLE 11
    [
        "A parlé de la Maif avec Martin M",
        "A travaillé pour La Poste",
        "A parlé de change avec Erwan",
        "A pris un télésiège avec Stéphane",
        "A un animal de compagnie",
        "A fait une photo influenceuse au sommet",
        "A descendu une piste noire (sans tomber)",
        "Offrir un shot à quelqu'un",
        "Faire une photo d'équipe sur le télésiège",
    ],
    # GRILLE 12
    [
        "A pris une photo avec quelqu'un qui travaille pour la SNCF dans le train / gare",
        "A fait un discours",
        "A descendu une piste noire (sans tomber)",
        "A fait rire 5 personnes avec la même blague",
        "A déjà skié dans 3 pays différents",
        "Offrir un shot à quelqu'un",
        "Quelqu'un qui parle 3 langues",
        "A eu un call client pendant le weekend",
        "Quelqu'un qui a déjà perdu ses skis / bâtons",
    ],
    # GRILLE 13
    [
        "A rejoint l'entreprise cette année",
        "N'a pas la nationalité Française",
        "A collé un sticker AI Builders sur les pistes",
        "A fait du snowboard",
        "A sorti son ordi sur les pistes",
        "A déjà skié dans 3 pays différents",
        "A déjà perdu ses skis",
        "Est sur une selfie d'Emmanuel",
        "A fait un discours",
    ],
    # GRILLE 14
    [
        "A chanté une chanson en karaoké",
        "Faire un selfie avec 3 collègues",
        "Faire une photo d'équipe sur le télésiège",
        "Quelqu'un qui est né le même mois que toi",
        "A skié sans veste",
        "A parlé de change avec Erwan",
        "A déjà perdu ses skis",
        "Quelqu'un qui parle 3 langues",
        "A fait du snowboard",
    ],
    # GRILLE 15
    [
        "A fait un selfie avec toute l'équipe LV présente",
        "A envoyé un mail pro sur une piste",
        "Quelqu'un qui déteste le ski",
        "A travaillé pour La Poste",
        "A collé un sticker AI Builders sur les pistes",
        "A parlé de moto avec Maxence",
        "A parlé du 16ème avec Nicolas",
        "A sorti son ordi sur les pistes",
        "Quelqu'un qui a un animal de compagnie",
    ],
]
